# Generated by Django 3.2.18 on 2023-05-28 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('license_plate', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(blank=True, max_length=45, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('generation', models.CharField(blank=True, max_length=45, null=True)),
                ('year_from', models.CharField(blank=True, max_length=200, null=True)),
                ('year_to', models.CharField(blank=True, max_length=200, null=True)),
                ('series', models.CharField(blank=True, max_length=200, null=True)),
                ('body_type', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_seats', models.CharField(blank=True, max_length=200, null=True)),
                ('length_mm', models.CharField(blank=True, max_length=200, null=True)),
                ('width_mm', models.CharField(blank=True, max_length=200, null=True)),
                ('height_mm', models.CharField(blank=True, max_length=200, null=True)),
                ('wheelbase_mm', models.CharField(blank=True, max_length=200, null=True)),
                ('front_track_mm', models.CharField(blank=True, max_length=200, null=True)),
                ('rear_track_mm', models.CharField(blank=True, max_length=200, null=True)),
                ('curb_weight_kg', models.CharField(blank=True, max_length=200, null=True)),
                ('ground_clearance_mm', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_hp', models.CharField(blank=True, max_length=200, null=True)),
                ('transmission', models.CharField(blank=True, max_length=200, null=True)),
                ('maximum_torque_n_m', models.CharField(blank=True, max_length=200, null=True)),
                ('acceleration_0_100_km_h_s', models.CharField(blank=True, db_column='acceleration_0_100_km/h_s', max_length=200, null=True)),
                ('max_speed_km_per_h', models.CharField(blank=True, max_length=200, null=True)),
                ('fuel_tank_capacity_l', models.CharField(blank=True, max_length=200, null=True)),
                ('city_fuel_per_100km_l', models.CharField(blank=True, max_length=200, null=True)),
                ('fuel_grade', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'car_specs',
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('city_province', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.CreateModel(
            name='RegisterCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city_province', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'register_center',
            },
        ),
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('license_plate', models.ForeignKey(db_column='license_plate', on_delete=django.db.models.deletion.DO_NOTHING, to='Registration.cars')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to='Registration.owners')),
                ('register_center', models.ForeignKey(db_column='register_center', on_delete=django.db.models.deletion.DO_NOTHING, to='Registration.registercenter')),
            ],
            options={
                'db_table': 'register_data',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Registration.carspecs'),
        ),
    ]
