# Generated by Django 3.2.18 on 2023-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCenter',
            fields=[
                ('center_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'register_center',
                'managed': False,
            },
        ),
    ]
