# Generated by Django 3.2.18 on 2023-04-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_registercenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterCenter',
        ),
    ]
