# Generated by Django 3.2.18 on 2023-04-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_delete_registercenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCenter',
            fields=[
                ('center_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city_province', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'register_center',
                'managed': False,
            },
        ),
    ]
